#
# Automatic generated configuration for gowiththeflow.
# Do not edit this file manually.
#
{% if GoWithTheFlow.general.enabled == '1' %}
gowiththeflow_enable="YES"
{% else %}
gowiththeflow_enable="NO"
{% endif %}
