#!/bin/sh
#
# PROVIDE: gowiththeflow
# REQUIRE: NETWORKING
# KEYWORD: shutdown
#

. /etc/rc.subr

name=gowiththeflow
rcvar=gowiththeflow_enable
command=/usr/local/opnsense/scripts/gowiththeflow/gowiththeflowd.py
command_interpreter=/usr/local/bin/python3
pidfile="/var/run/${name}.pid"
load_rc_config $name

: ${gowiththeflow_enable:=NO}

stop_cmd=gowiththeflow_stop

gowiththeflow_stop()
{
    if [ -z "$rc_pid" ]; then
      [ -n "$rc_fast" ] && return 0
      _run_rc_notrunning
      return 1
    fi

    echo -n "Stopping ${name}."
    kill -15 ${rc_pid}

    for i in $(seq 1 50); do
        if [ -z "$(/bin/ps -ax | /usr/bin/awk '{print $1;}' | /usr/bin/grep "^${rc_pid}")" ]; then
            break
        fi
        sleep 0.1
    done

    for gowiththeflow_pid in $(/bin/ps -ax | grep 'gowiththeflowd.py' | /usr/bin/awk '{print $1;}'); do
       kill -9 $gowiththeflow_pid >/dev/null 2>&1
    done

    echo  "..done"
}

run_rc_command $1
